spring:
  application:
    name: job-application-tracker
  profiles:
    active: dev

jwt:
  expirationMinutes: 120

springdoc:
  swagger-ui:
    path: /swagger
  api-docs:
    path: /v3/api-docs

kafka:
  topics:
    interviewScheduled: interview-scheduled
